# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_IndexWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndexWidget(object):
    def setupUi(self, IndexWidget):
        IndexWidget.setObjectName("IndexWidget")
        IndexWidget.resize(1300, 740)
        self.horizontalLayout = QtWidgets.QHBoxLayout(IndexWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(IndexWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/img/妆糕人介绍.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(IndexWidget)
        QtCore.QMetaObject.connectSlotsByName(IndexWidget)

    def retranslateUi(self, IndexWidget):
        _translate = QtCore.QCoreApplication.translate
        IndexWidget.setWindowTitle(_translate("IndexWidget", "Form"))
import CakeDM_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IndexWidget = QtWidgets.QWidget()
    ui = Ui_IndexWidget()
    ui.setupUi(IndexWidget)
    IndexWidget.show()
    sys.exit(app.exec_())
