# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 562)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/妆字.gif"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 697, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_picture = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/图片.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_picture.setIcon(icon1)
        self.action_picture.setObjectName("action_picture")
        self.action_video = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/视频.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_video.setIcon(icon2)
        self.action_video.setObjectName("action_video")
        self.action_quit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/Quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_quit.setIcon(icon3)
        self.action_quit.setObjectName("action_quit")
        self.action_mini = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_mini.setIcon(icon4)
        self.action_mini.setObjectName("action_mini")
        self.action_close = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/img/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_close.setIcon(icon5)
        self.action_close.setObjectName("action_close")
        self.action_home = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/img/主页.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_home.setIcon(icon6)
        self.action_home.setObjectName("action_home")
        self.action_history = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/img/文档.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_history.setIcon(icon7)
        self.action_history.setObjectName("action_history")
        self.action_man = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/img/人物.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_man.setIcon(icon8)
        self.action_man.setObjectName("action_man")
        self.toolBar.addAction(self.action_home)
        self.toolBar.addAction(self.action_picture)
        self.toolBar.addAction(self.action_video)
        self.toolBar.addAction(self.action_history)
        self.toolBar.addAction(self.action_man)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_close)
        self.toolBar.addAction(self.action_mini)
        self.toolBar.addAction(self.action_quit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "妆糕人数据库"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_picture.setText(_translate("MainWindow", "图片"))
        self.action_picture.setToolTip(_translate("MainWindow", "图片库"))
        self.action_video.setText(_translate("MainWindow", "视频"))
        self.action_video.setToolTip(_translate("MainWindow", "视频库"))
        self.action_quit.setText(_translate("MainWindow", "退出"))
        self.action_mini.setText(_translate("MainWindow", "最小化"))
        self.action_close.setText(_translate("MainWindow", "关闭所有页面"))
        self.action_home.setText(_translate("MainWindow", "主页"))
        self.action_history.setText(_translate("MainWindow", "史料库"))
        self.action_man.setText(_translate("MainWindow", "非遗传承人"))
import CakeDM_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
